version: "3.8"

services:
  app:
    image: micronautguide:latest
    ports:
      - "8080:8080"
    environment:
      # Enable Micronaut's built-in JWT login endpoint at /auth/login
      MICRONAUT_SECURITY_TOKEN_JWT_LOGIN_ENABLED: "true"
      MICRONAUT_SECURITY_TOKEN_JWT_LOGIN_PATH: "/auth/login"
      
      # JWT secret: must be at least 64 characters for HS256
      MICRONAUT_SECURITY_TOKEN_JWT_SIGNATURES_SECRET_GENERATOR_SECRET: "64characterSecretKeyRequiredForHS256Algorithm1234567890!!"
      MICRONAUT_SECURITY_TOKEN_JWT_SIGNATURES_ALGORITHM: HS256
      
      # Enable Micronaut security and bearer token authentication
      MICRONAUT_SECURITY_ENABLED: "true"
      MICRONAUT_SECURITY_AUTHENTICATION: "bearer"

      # Native image memory tuning (optional)
      GRAALVM_DEBUG: "true"
      JAVA_OPTS: "-XX:MaximumHeapSizePercent=80 -XX:MaxRAMPercentage=75.0"

      # Database config
      MICRONAUT_SERVER_PORT: 8080
      DATASOURCES_DEFAULT_URL: jdbc:postgresql://db:5432/testdb
      DATASOURCES_DEFAULT_USERNAME: test
      DATASOURCES_DEFAULT_PASSWORD: test
      DATASOURCES_DEFAULT_DRIVER_CLASS_NAME: org.postgresql.Driver
      JPA_DEFAULT_PROPERTIES_HIBERNATE_HBM2DDL_AUTO: update
      MICRONAUT_DATA_PACKAGES: example.micronaut
      JPA_DEFAULT_ENTITY_SCAN_PACKAGES: example.micronaut

      # Detailed logging for security debugging
      LOGGING_LEVEL_IO_MICRONAUT_SECURITY: DEBUG
      LOGGING_LEVEL_IO_MICRONAUT_SECURITY_FILTERS: TRACE
      LOGGING_LEVEL_IO_MICRONAUT_SECURITY_AUTHENTICATION: TRACE
      LOGGING_LEVEL_IO_MICRONAUT_SECURITY_RULES: DEBUG
      LOGGING_LEVEL_IO_MICRONAUT_SECURITY_TOKEN: TRACE
      LOGGING_LEVEL_IO_MICRONAUT_SECURITY_TOKEN_JWT: TRACE

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
