version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

